### PR TITLE
Add keywords and operator related to full-text indexing & search

### PR DESCRIPTION
**Pull request by emmanuel-keller**
This introduces the keywords and operators added by the full-text capabilities.

@kearfy One thing is missing, the operator matches @@ can have a reference: Eg.: @1@

Can we use regular expression in operators.txt?

```
@([a-zA-Z0-9*)@ 
```

### CODE REVIEW

**Comment by kearfy** [comment]
You forgot the `]` (`@([a-zA-Z0-9]*)@`), but yeah, that should work! If you can added that to the list of operators I'd say it's ready to merge!

**Comment by emmanuel-keller** [comment]
In fact they are just numbers. Is this the expected syntax ? In `keywords.txt` I see that we are using  `( ... )?`.

    @([0-9]*)?@

**Comment by kearfy** [comment]
Those files were a way for me to organize the language for me during writing all of this. Will replace them at some point with something better. Nothing functional, just a huge mental note xd

**Comment by kearfy** [comment]
Let's pick either of the two:
- `@([0-9]+)?@`
- `@([0-9]*)@`

**Comment by emmanuel-keller** [comment]
It is longer, but I find the semantic of these one closer:

    @([0-9]+)?@
   
 Committed

**Comment by kearfy** [comment]
Apologies, I meant in the list of operators in the actual tmLanguage file. Something like this should do:

```JSON
{
    "name": "keyword.operator.matches.surrealql",
    "match": "@([0-9]+)?@",
    "captures": {
        "1": {
            "name": "constant.numeric.int"
        }
    }
}
```

**Comment by emmanuel-keller** [comment]
Ok, done.. I have prettier enabled in my env, making the diff being a little bit bigger than it should. Is it okay with you?

**Review by kearfy — APPROVED** [review]

**Pull request merged**
